UMC-CARDIFY/CARDIFY-Frontend

package-lock.json
package.json
src/App.jsx
src/pages/SignIn.jsx
src/styles/MediaQuery.jsx

- close #2
- 로그인 페이지 와이어프레임 구현
반응형 웹을 위한 미디어 쿼리 파일을 작성했습니다.

[Feat] 로그인 페이지 와이어프레임 구현

---

src/App.jsx
src/pages/Archive/index.jsx
src/pages/Dashboard/index.jsx
src/pages/MyPage/index.jsx
src/pages/SignIn/index.jsx
src/pages/index.js
src/routes/index.jsx

[Feat] 프로젝트 구조 설정

---

src/pages/SignIn/index.jsx
src/pages/SignUp/index.jsx

- 로그인 화면 랩탑 사이즈 화면 추가
- 회원가입 비밀번호 입력창 눈 모양 위치 안맞음 수정

Chore: 로그인 화면 랩탑 사이즈 추가, 회원가입 화면 디자인 수정

---

src/pages/MyPage/PointPage.jsx
src/pages/MyPage/SubscriptionPage.jsx
src/pages/MyPage/components/BackButton.jsx
src/pages/MyPage/components/LogoutButton.jsx
src/pages/MyPage/components/Switch.jsx
src/pages/MyPage/index.jsx
src/pages/index.js
src/routes/index.jsx

- close #18
- 마이페이지/포인트 화면 와이어프레임 구현
- 마이페이지/요금제 화면 와이어프레임 구현
- 반응형 구현
- Logout 버튼, 뒤로가기 버튼, Switch 컴포넌트 분리 
- 마이페이지 스타일 수정

[Feat] 포인트 및 요금제 와이어프레임 구현 완료

---

package-lock.json
package.json
src/api/archive/dummyData.js
src/components/MenuBar.jsx
src/components/TopBar.jsx
src/pages/Archive/components/Frame.jsx
src/pages/Archive/index.jsx

- close #12 
- 폴더 페이지네이션 구현
- 더미데이터 연결
- 화면 ui 구성
- 반응형은 아직 미완입니다.

Feat/#12 아카이브 페이지 ui 구현

---

src/pages/Dashboard/components/RecentNote/RecentNoteItem.jsx
src/pages/Dashboard/components/RecentNote/RecentNotes.jsx
src/pages/Dashboard/components/StudySuggestion/StudyCalendar.jsx
src/pages/Dashboard/components/StudySuggestion/StudyCard.jsx
src/pages/Dashboard/components/StudySuggestion/StudySuggestions.jsx
src/pages/Dashboard/components/WeeklyStudy/DayBar.jsx
src/pages/Dashboard/components/WeeklyStudy/WeeklyStudyResults.jsx
src/pages/Dashboard/index.jsx

[Style] 대시보드 화면 컬러, 폰트 수정

---

package-lock.json
package.json
src/pages/NoteEditor/components/Editor/Content.jsx
src/pages/NoteEditor/components/Editor/Title.jsx
src/pages/NoteEditor/components/Editor/index.jsx
src/pages/NoteEditor/components/Header.jsx
src/pages/NoteEditor/components/MenuBar.jsx
src/pages/NoteEditor/index.jsx
src/pages/index.js
src/routes/index.jsx

-마크다운 구현 중...
- 이탤릭체, 밑줄 적용
볼드체는 아직 해결 중

[Feat] 노트에디터 마크다운

---

src/components/MenuBar.jsx
src/components/TopBar.jsx
src/pages/Dashboard/index.jsx

- close #23
- 메뉴바 프로토타입 UI 및 기능 구현
- 탑바 프로토타입 UI 및 기능 구현
- 메뉴바/탑바 반응형 구현
- 메뉴 hover 시 글씨 색만 바뀌고 아이콘 stroke 색은 바뀌지 않음
- 메뉴 글씨 부분 정렬 안 맞음

Feat/#23 메뉴바 탑바 프로토타입 구현

---

src/pages/NoteEditor/components/Editor/ToolBar.jsx
src/pages/NoteEditor/components/Editor/index.jsx

🔑 주요 변경사항
노트에디터 화면 툴바 구현 (일단 텍스트로 설명)
✔️ 체크 리스트
-[] Merge 하려는 브랜치가 올바른가? (main branch에 실수로 PR 생성 금지)
-[] Merge 하려는 PR 및 Commit들을 로컬에서 실행했을 때 에러가 발생하지 않았는가?

[Feat] 노트에디터 툴바 구현

---

src/pages/NoteEditor/components/Header.jsx

- close #33 
- 노트에디터 검색창 기능 구현

[Feat] 노트에디터 검색창 기능 구현

---

src/components/MenuBar.jsx
src/components/TopBar.jsx
src/pages/Archive/components/DeleteConfirmModal.jsx
src/pages/Archive/components/Frame.jsx
src/pages/Archive/components/MoreDiv.jsx

🚀 관련 이슈
close #32 
🔑 주요 변경사항
아카이브 페이지 더보기 버튼 구현
폴더/노트 삭제 모달 구현
✔️ 체크 리스트
-[] Merge 하려는 브랜치가 올바른가? (main branch에 실수로 PR 생성 금지)
-[] Merge 하려는 PR 및 Commit들을 로컬에서 실행했을 때 에러가 발생하지 않았는가?

[Feat] 아카이브 폴더 노트 삭제 모달 구현

---

src/pages/NoteEditor/components/Header.jsx
src/pages/NoteEditor/components/MenuBar.jsx
src/pages/NoteEditor/index.jsx

- #39 
- 메뉴바 밀기 기능 추가
헤더 길이 안 늘어나는 에러 있음

[Feat] 메뉴바 밀기 기능 추가 중

---

src/pages/NoteEditor/components/Editor/Content.jsx
src/pages/NoteEditor/components/Editor/ToolBar.jsx
src/pages/NoteEditor/components/Editor/index.jsx

- close #38 
- 노트에디터 가림판카드 구현 중에 있습니다

[Feat] 노트에디터 가림판카드

---

src/pages/SignUp/index.jsx
src/pages/SignUp/useFormValidation.jsx
src/pages/SignUp/validation.jsx

[Feat] 회원가입 페이지 프로토 구현완료

---

src/api/config.js
src/api/signin/signin.js
src/pages/SignIn/index.jsx

 [Feat] 로그인 페이지 api 연동 진행 중

---

src/api/signup/signup.js
src/pages/SignUp/index.jsx
src/pages/SignUp/useFormValidation.jsx
src/pages/SignUp/validation.jsx

- close #51
- 회원가입 페이지 프로토 수정
- 회원가입 페이지 api 연동 중

[Feat] 회원가입 페이지 api 연동 진행 중

---

src/App.jsx
src/api/editor/card/imagecard.js
src/pages/NoteEditor/components/Cards/ImageCard.jsx
src/pages/NoteEditor/components/Header.jsx
src/pages/NoteEditor/components/SaveContext.jsx

- 헤더의 저장하기 버튼 눌러서 서버로 가림판카드 전송
- 편집 모달 추가 (아직 편집 기능 x)

Feat/#52 가림판카드 api 연동

---

src/api/archive/getFolders.js
src/api/index.js
src/api/signin/signin.js
src/pages/Archive/components/Frame.jsx
src/pages/Archive/index.jsx

- close #63 
- localStorage에 accessToken 저장
- 폴더 조회 api 연결

[Feat] 아카이브 페이지 폴더 조회 기능 api 연결

---

src/pages/NoteEditor/components/Header.jsx

- 가림판 카드 저장 안할시 alert창 띄우지 않도록 수정

fix: 저장하기 버튼 기능 수정

---

src/api/NoteContext.jsx
src/api/index.js
src/api/noteeditor/getNote.js
src/main.jsx
src/pages/NoteEditor/components/Editor/CombinedEditor.jsx
src/pages/NoteEditor/components/Editor/Toolbar/ToolBar.jsx
src/pages/NoteEditor/components/Editor/Toolbar/components/ToolbarItem/ColorPalette/HighlightColorPalette.jsx
src/pages/NoteEditor/components/Editor/Toolbar/components/ToolbarItem/ColorPalette/TextColorPalette.jsx
src/pages/NoteEditor/components/Editor/Toolbar/components/ToolbarItem/HeadingButton.jsx
src/pages/NoteEditor/components/Editor/Toolbar/components/ToolbarItem/HighlightColorButton.jsx
src/pages/NoteEditor/components/Editor/Toolbar/components/ToolbarItem/TextColorButton.jsx
src/pages/NoteEditor/components/Editor/index.jsx
src/pages/NoteEditor/components/Editor/setup/blankcardView.js
src/pages/NoteEditor/components/Editor/setup/multicardView.js
src/pages/NoteEditor/components/Editor/setup/schema.jsx
src/pages/NoteEditor/components/Editor/setup/wordcardView.js
src/pages/NoteEditor/components/Header/Header.jsx
src/pages/NoteEditor/components/Header/KebabMenu/DeleteMenu.jsx
src/pages/NoteEditor/components/Header/KebabMenu/KebabMenu.jsx
src/pages/NoteEditor/components/Header/KebabMenu/ShareMenu.jsx
src/pages/NoteEditor/components/MenuBar.jsx
src/pages/NoteEditor/index.jsx

- #71
- 노트에디터 메뉴바 노트조회 api 연동
- 노트에디터 툴바 기능 추가
- 카드노드 attrs 앞면 question_front로 수정

[Feat] 노트에디터 노트조회 api 연동

---

src/api/dashboard/recentNotes.js
src/api/index.js
src/pages/Dashboard/components/RecentNote/RecentNotes.jsx

[Feat] 대시보드 최근 열람한 노트 api 연결

---

.gitignore
src/api/config.js
src/api/index.js

[chore] 설정 파일 .env로 API URL과 클라이언트 ID 관리

---

vite.config.js

- #88 
- proxy target 배포 url로 수정

[chore] proxy target 배포 url로 수정

---

src/pages/SignIn/index.jsx

[chore] 배포 테스트용 코드 수정

---

src/pages/SignIn/index.jsx

- #88 
- 자동 배포 테스트용으로 로그인 페이지 코드 수정

[chore] 자동 배포 테스트용

---

src/pages/Archive/components/ItemList.jsx

- close #97 
- 노트 클릭 시 노트페이지로 전환되도록 기능 구현

[Feat] 노트 클릭 시 노트페이지로 전환되도록 기능 구현

---

src/api/library/download.js
src/pages/Library/components/NoteItem.jsx
src/pages/Library/components/NoteModal.jsx

- close #102
- 노트 다운로드 받을때 내가 공유 중인 노트일 경우 그 노트로 이동

[Feat] 자료실 노트에디터 이동

---

src/pages/NoteEditor/components/Editor/setup/multicardView.js

- #71 
- 멀티카드 뒷면 불렛 위치 및 스타일 조정

[Chore] 멀티카드 뒷면 불렛 오류 해결

---

src/main.jsx
src/styles/global.css

[Style] 폰트 스타일 적용

---

src/api/common/selectFolderModal/writeNote.js
src/components/Modal/SelectFolderModal.jsx

- close #112 
- 폴더 선택 모달 노트 추가 기능까지 구현 완료

[feat] 폴더 선택 모달 구현 완료

---

src/pages/Library/components/NoteList.jsx
src/pages/Library/components/SelectFolderModal.jsx
src/pages/Library/index.jsx

- close #119
- 첫화면 계속 노트 조회 api 호출되는 문제 수정

[fix] 첫화면 계속 api 호출되는 문제 수정

---

src/api/noteeditor/postNoteSearch.js
src/assets/arrow.svg
src/pages/NoteEditor/components/Editor/Toolbar/components/ToolbarItem/TextColorButton.jsx
src/pages/NoteEditor/components/Editor/Toolbar/components/ToolbarItem/style/ToolbarStyles.jsx
src/pages/NoteEditor/components/Header/SearchInput.jsx

- close #121 
- 헤딩, 텍스트 컬러, 하이라이트 드롭다운 위치 변경
- 검색바 api 연결
- 검색 모달 스타일 적용

[Feat] 노트에디터 툴바 기능 및 스타일 수정

---

src/pages/Library/components/NoteModal.jsx
src/pages/Library/components/NotePreview.jsx

- #116
- 자료실 노트 미리보기 모달 노트내용 prosemirror 및 렌더링 추가

[Feat] 자료실 노트 미리보기 렌더링 추가

---

src/api/library/download.js
src/pages/Library/components/NoteItem.jsx
src/pages/Library/components/NoteList.jsx
src/pages/Library/components/NoteModal.jsx

- close #125
-  다운로드 방식 편집 허용, 불가로 변경

[feat] 다운로드 방식 편집 허용, 불가로 변경

---

src/api/noteeditor/cancelShare.js
src/pages/NoteEditor/components/Header/KebabMenu/ShareMenu.jsx

- close #124 
- 자료실 공유취소 api 추가 및 연동

[Feat] 자료실 공유취소 기능구현

---

src/api/mypage/userCheck.js
src/pages/MyPage/components/AttendanceButton.jsx
src/pages/MyPage/index.jsx

- close #132 
- 유저 출석체크 api 연동
- 출석 상태에 따른 출석버튼 ux/ui 수정

[Feat] 마이페이지 출석체크 구현완료

---

src/pages/Flashcard/components/AnalysisStudyModal.jsx
src/pages/Flashcard/components/CommonStudyModal.jsx

- close #138
- ui 수정 및 멀티카드 난이도 선택 기능 수정

[Feat] 분석학습 기능 수정

---

src/pages/SignIn/index.jsx

[feat] 로그인 엔터 기능 추가

---

src/components/Modal/SelectFolderModal.jsx
src/pages/Dashboard/components/RecentNote/RecentNoteItem.jsx
src/pages/NoteEditor/components/MenuBar.jsx

- close #145 
- lavender 색 안 넘어오는 에러 수정

[fix] lavender 색 안 넘어오는 에러 수정

---

src/pages/Archive/components/Circle.jsx
src/pages/Archive/components/SortDropdown.jsx

- close #148 
- 아카이브 필터링 오류 수정

[Fix] 아카이브 필터링 오류 수정

---

src/pages/Archive/components/CircleCheck.jsx
src/pages/Archive/components/FilteringDropdown.jsx

[Fix] 필터링 오류 수정

---

src/pages/Library/components/NoteModal.jsx
src/pages/Library/index.jsx

- close #155
- 미리보기 내용 길어지면 스크롤

[feat] 미리보기 내용 길어지면 스크롤

---

src/api/noteeditor/imageCard/addImageCard.js
src/api/noteeditor/imageCard/getImageCard.js
src/pages/NoteEditor/components/Cards/ImageCard.jsx

[Feat] 이미지카드 컨테이너 스타일 수정

---

src/styles/GlobalStyle.jsx

feat: 전역 스타일 폰트 적용

---

src/assets/addIcon.svg
src/pages/Archive/components/AddButton.jsx
src/pages/Archive/components/ItemList.jsx
src/pages/Flashcard/components/CompletionModal.jsx
src/pages/Library/components/RecommendationSection.jsx
src/pages/Library/index.jsx
src/styles/GlobalStyle.jsx

[Feat] 폰트 스타일 수정

---

src/pages/Flashcard/index.jsx

- #161 
- 플래시카드 스크롤 메뉴바 안 늘어나게 수정

[style] 플래시카드 스크롤 메뉴바 안 늘어나게 수정

---

src/pages/Archive/components/ItemList.jsx

[style] 아카이브 ux ui 수정

---

src/api/editor/card/imagecard.js
src/api/noteeditor/imageCard/getNote.js
src/pages/NoteEditor/components/Cards/ImageCard.jsx
src/pages/NoteEditor/index.jsx

[Feat] 노트에디터 이미지 카드 api 연결

---

src/pages/Library/components/NoteItem.jsx
src/pages/Library/index.jsx

[Feat] 자료실 UI 수정

---

src/pages/Library/components/CategoryCheck.jsx
src/pages/Library/index.jsx

[feat] 카테고리 체크 표시 테스트

---

src/pages/Dashboard/components/StudySuggestion/StudyCard.jsx

- #83 
- 학습제안 학습하기로 안 뜨고 음수로 뜨는 에러 수정

[fix] 학습제안 학습하기로 안 뜨고 음수로 뜨는 에러 수정

---

src/pages/Library/components/CategoryCheck.jsx

fix: 카테고리 호버링 추가

---

src/pages/Dashboard/components/StudySuggestion/StudyCalendar.jsx

- #83 
- 학습제안 캘린더 호버 클릭 스타일 수정

[style] 학습제안 캘린더 호버 클릭 스타일 수정

---

src/pages/Flashcard/components/CompletionModal.jsx

[fix] 모달 적용안되는 오류 해결 중

---

src/pages/Flashcard/components/CommonStudyModal.jsx
src/pages/Flashcard/components/CompletionModal.jsx

[Feat] qa 반영

---

src/pages/NoteEditor/components/Editor/Toolbar/components/ToolbarItem/MoreOptions/MoreOptions.jsx

[Feat] 노트에디터 툴바 더보기 디자인

---

src/pages/NoteEditor/components/Editor/Toolbar/ToolBar.jsx
src/pages/NoteEditor/components/Editor/Toolbar/components/ToolbarItem/MoreOptions/MoreOptions.jsx

- #83 
- 텍스트 블록 추가 툴바에 기본으로 뜨게 수정

[feat] 텍스트 블록 추가 툴바에 기본으로 뜨게 수정
